"""002_init

Revision ID: db50e3313b3e
Revises: fd34cbed3bde
Create Date: 2024-09-06 04:30:28.171560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db50e3313b3e'
down_revision: Union[str, None] = 'fd34cbed3bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operations_email', table_name='operations')
    op.drop_column('operations', 'is_superuser')
    op.drop_column('operations', 'is_active')
    op.drop_column('operations', 'hashed_password')
    op.drop_column('operations', 'email')
    op.drop_column('operations', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
    op.add_column('operations', sa.Column('email', sa.VARCHAR(length=320), nullable=False))
    op.add_column('operations', sa.Column('hashed_password', sa.VARCHAR(length=1024), nullable=False))
    op.add_column('operations', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.add_column('operations', sa.Column('is_superuser', sa.BOOLEAN(), nullable=False))
    op.create_index('ix_operations_email', 'operations', ['email'], unique=1)
    # ### end Alembic commands ###
